---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - robertdebock.bootstrap
    - robertdebock.update
  
  vars:
    # For APT (Debian/Ubuntu) only: remove unused dependency packages for all module states except `build-dep'
    update_autoremove: yes

    # For APT (Debian/Ubuntu) only: apt_upgrade type which can be: dist, full, yes, or safe
    update_upgrade_command: full

    # For APT (Debian/Ubuntu) only: update the apt cache if it's older than the cache_valid_time.  Set in seconds.
    update_cache_valid_time: 1

    # When updating systems, a reboot may be required. Here you can select to:
    # "yes": Always reboot when packages have changed.
    # "no": Never reboot when packages have changed.
    update_reboot: yes
